[package]
name = "pxtone-sys"
description = "Low level bindings to pxtone for Rust"
repository = "https://github.com/PieKing1215/rust-pxtone-sys"
version = "0.1.0"
authors = ["PieKing1215"]
links = "pxtone"
build = "src/build.rs"
edition = "2018"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }

[dev-dependencies]
cpal = "0.13"